version: "3.8"
volumes:
  postgres:
services:
  app:
    build:
      context: .
      target: base
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./app/data:/data
    environment:
      POSTGRES_DB: covid_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

